"""add_rag_and_bookmark_fields

Revision ID: bca66cdae8c4
Revises: f1698a6524de
Create Date: 2025-12-31 15:41:56.925289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bca66cdae8c4'
down_revision: Union[str, Sequence[str], None] = 'f1698a6524de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"PRAGMA table_info({table_name})"))
    columns = [row[1] for row in result]
    return column_name in columns


def upgrade() -> None:
    """Upgrade schema."""
    # Handle partial migration state - only add columns that don't exist
    if not column_exists('generated_ideas', 'market_signals'):
        op.add_column('generated_ideas', sa.Column('market_signals', sqlite.JSON(), nullable=True))
    if not column_exists('generated_ideas', 'confidence_score'):
        op.add_column('generated_ideas', sa.Column('confidence_score', sa.Float(), nullable=True))
    if not column_exists('generated_ideas', 'is_bookmarked'):
        op.add_column('generated_ideas', sa.Column('is_bookmarked', sa.Boolean(), nullable=False, server_default=sa.false()))
    if not column_exists('generation_sessions', 'rag_context'):
        op.add_column('generation_sessions', sa.Column('rag_context', sqlite.JSON(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_sessions', 'rag_context')
    op.drop_column('generated_ideas', 'is_bookmarked')
    op.drop_column('generated_ideas', 'confidence_score')
    op.drop_column('generated_ideas', 'market_signals')
    # ### end Alembic commands ###
