"""initial_schema

Revision ID: f0dcfaa407c4
Revises: 
Create Date: 2025-12-28 23:08:27.159200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f0dcfaa407c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('INITIAL_LOAD', 'INCREMENTAL', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('target_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posts_collected', sa.Integer(), nullable=True),
    sa.Column('posts_processed', sa.Integer(), nullable=True),
    sa.Column('posts_filtered', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('keywords', sqlite.JSON(), nullable=False),
    sa.Column('domain_tag', sa.String(length=50), nullable=False),
    sa.Column('trend', sa.Enum('RISING', 'STABLE', 'DECLINING', name='trend'), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentiment'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('raw_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_hash', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_job_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['collection_job_id'], ['collection_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_posts')
    op.drop_table('document_summaries')
    op.drop_table('collection_jobs')
    # ### end Alembic commands ###
