"""add_stage_b_tables

Revision ID: f1698a6524de
Revises: 3bbc8d2033cd
Create Date: 2025-12-29 16:36:58.907296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f1698a6524de'
down_revision: Union[str, Sequence[str], None] = '3bbc8d2033cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_sessions_problem_id', 'generation_sessions', ['problem_id'], unique=False)
    op.create_index('ix_generation_sessions_user_id', 'generation_sessions', ['user_id'], unique=False)
    op.create_table('generated_ideas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('differentiators', sqlite.JSON(), nullable=False),
    sa.Column('market_opportunity', sa.Text(), nullable=False),
    sa.Column('implementation_hints', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['generation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_ideas_session_id', 'generated_ideas', ['session_id'], unique=False)
    op.create_table('saved_ideas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['generated_ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idea_id', name='uq_user_idea')
    )
    op.create_index('ix_saved_ideas_idea_id', 'saved_ideas', ['idea_id'], unique=False)
    op.create_index('ix_saved_ideas_user_id', 'saved_ideas', ['user_id'], unique=False)
    op.drop_index(op.f('ix_document_relationships_source'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_target'), table_name='document_relationships')
    op.create_index(op.f('ix_document_relationships_source_document_id'), 'document_relationships', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_relationships_target_document_id'), 'document_relationships', ['target_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_relationships_target_document_id'), table_name='document_relationships')
    op.drop_index(op.f('ix_document_relationships_source_document_id'), table_name='document_relationships')
    op.create_index(op.f('ix_document_relationships_target'), 'document_relationships', ['target_document_id'], unique=False)
    op.create_index(op.f('ix_document_relationships_source'), 'document_relationships', ['source_document_id'], unique=False)
    op.drop_index('ix_saved_ideas_user_id', table_name='saved_ideas')
    op.drop_index('ix_saved_ideas_idea_id', table_name='saved_ideas')
    op.drop_table('saved_ideas')
    op.drop_index('ix_generated_ideas_session_id', table_name='generated_ideas')
    op.drop_table('generated_ideas')
    op.drop_index('ix_generation_sessions_user_id', table_name='generation_sessions')
    op.drop_index('ix_generation_sessions_problem_id', table_name='generation_sessions')
    op.drop_table('generation_sessions')
    # ### end Alembic commands ###
