"""GeneratedIdea model for AI-generated business ideas."""

from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import uuid4

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, String, Text
from sqlalchemy.dialects.sqlite import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.storage import Base

if TYPE_CHECKING:
    from src.models.generation_session import GenerationSession
    from src.models.saved_idea import SavedIdea


class GeneratedIdea(Base):
    """An individual business idea generated by the AI agent."""

    __tablename__ = "generated_ideas"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid4())
    )
    session_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("generation_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    target_audience: Mapped[str] = mapped_column(Text, nullable=False)
    differentiators: Mapped[list] = mapped_column(
        JSON, nullable=False, default=list
    )  # List of key differentiators
    market_opportunity: Mapped[str] = mapped_column(Text, nullable=False)
    implementation_hints: Mapped[str] = mapped_column(Text, nullable=False)
    # New fields for RAG and bookmarking
    market_signals: Mapped[Optional[list]] = mapped_column(
        JSON, nullable=True, default=list
    )  # References to market data from RAG context
    confidence_score: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, default=None
    )  # 0.0-1.0 score based on how well idea is grounded in data
    is_bookmarked: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )  # Whether user has bookmarked this idea
    is_deleted: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )  # Soft delete flag (user can remove from My Ideas)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=datetime.utcnow
    )

    # Relationships
    session: Mapped["GenerationSession"] = relationship(
        "GenerationSession", back_populates="ideas"
    )
    saved_by: Mapped[list["SavedIdea"]] = relationship(
        "SavedIdea", back_populates="idea", cascade="all, delete-orphan"
    )

    __table_args__ = (Index("ix_generated_ideas_session_id", "session_id"),)
